data_file: Aeroshield_with_deriv
output_file_name: "Aeroshield/Aeroshield_data"
log_file_name: "Aeroshield/Aeroshield_log"
time_step: 0.01
include_control_input: True
perturb_input_signal: False
filter_data: False
column_indices: [0, 1, 2]
processors: 8
random_seed: 42
val_size: 0.25
test_size: 0.25
num_trajectories: 5
constraints:
  sim_steps: 350
  coeff_precision: null
  max_complexity: 12
  max_coeff: 350.0
  min_r2: 0.6
  max_state: 3.0
